### ISSUE TITLE
Terminate docker image

### ISSUE THREAD

**Issue by izenoni** [andersnas/nodecat#2]
Could not easily stop the docker container with ctrl-c, had to `docker kill ps` to stop it.
Added the following tokenManger.js to gracefully stopped the container
```
process.on('SIGINT', () => {
  console.info("Interrupted");
  process.exit(0);
})
```
Happy to branch and PR the above change.

**Comment by andersnas** [comment]
Please go ahead! Great input.

**Comment by izenoni** [comment]
attempted to create a branch and push, failed:
ERROR: Permission to andersnas/nodecat.git denied to izenoni.
